source.dinosnominalsubgroupdiscovery.jar = src/
bin.includes = plugin.xml,\
               META-INF/,\
               dinosnominalsubgroupdiscovery.jar,\
               lib/DAF.jar,\
               lib/classgraph.jar,\