source.dinosnominalsubgroupdiscovery.jar = src/
bin.includes = plugin.xml,\
               META-INF/,\
               dinosnominalsubgroupdiscovery.jar,\
               DAF.jar,\
               classgraph.jar
